#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../terraform"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ─────────────────────────────────────────────────────────────────────────────
# Prerequisites
# ─────────────────────────────────────────────────────────────────────────────
for cmd in terraform aws kubectl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo -e "${RED}Error: $cmd is required but not installed${NC}"
    exit 1
  fi
done

# ─────────────────────────────────────────────────────────────────────────────
# Workshop shortcut: ./install.sh workshop
# ─────────────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "workshop" ]]; then
  echo -e "${GREEN}=== OpenClaw EKS — Workshop Mode ===${NC}"
  echo "Profile: ARM64 Graviton, no Firecracker, with admin console"
  echo ""
  cd "$TF_DIR"
  terraform init -input=false
  terraform apply -var-file=profiles/workshop.tfvars -auto-approve
  echo ""
  echo -e "${GREEN}=== Done ===${NC}"
  terraform output -raw configure_kubectl
  echo ""
  exit 0
fi

# ─────────────────────────────────────────────────────────────────────────────
# Interactive wizard
# ─────────────────────────────────────────────────────────────────────────────
clear 2>/dev/null || true
echo ""
echo -e "${GREEN}${BOLD}  ╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}  ║     OpenClaw on EKS — Deployment Wizard     ║${NC}"
echo -e "${GREEN}${BOLD}  ╚══════════════════════════════════════════════╝${NC}"
echo ""

# --- Region ---
DETECTED_REGION=$(aws configure get region 2>/dev/null || echo "us-west-2")
read -rp "  AWS Region [${DETECTED_REGION}]: " INPUT_REGION
REGION="${INPUT_REGION:-$DETECTED_REGION}"

IS_CHINA=false
[[ "$REGION" == cn-* ]] && IS_CHINA=true

# --- Cluster name ---
DEFAULT_NAME="openclaw-eks"
read -rp "  Cluster name [${DEFAULT_NAME}]: " INPUT_NAME
NAME="${INPUT_NAME:-$DEFAULT_NAME}"

# --- Architecture ---
echo ""
echo -e "  ${CYAN}Architecture${NC}"
echo "    1) ARM64 (Graviton) — recommended, ~30% cheaper"
echo "    2) x86 (Intel/AMD)"
read -rp "  Select [1]: " ARCH_CHOICE
case "${ARCH_CHOICE:-1}" in
  1) ARCH="arm64" ;;
  2) ARCH="x86" ;;
  *) echo -e "${RED}Invalid${NC}"; exit 1 ;;
esac

# --- Firecracker ---
echo ""
echo -e "  ${CYAN}Kata Containers with Firecracker${NC}"
echo "    VM-level isolation — each OpenClaw instance runs in a Firecracker microVM."
echo "    Requires bare-metal nodes (c6g.metal / m5.metal, ~\$4/hr on-demand)."
echo "    Nodes auto-scale via Karpenter (scale to zero when idle)."
read -rp "  Enable Firecracker? [y/N]: " FC_CHOICE
ENABLE_FC=false
ENABLE_KARPENTER=false
if [[ "${FC_CHOICE}" =~ ^[yY]$ ]]; then
  ENABLE_FC=true
  ENABLE_KARPENTER=true
fi

# --- Admin Console ---
echo ""
echo -e "  ${CYAN}Enterprise Admin Console${NC}"
echo "    Deploys the admin console (DynamoDB + S3 + gateway) on an EC2 instance"
echo "    alongside the EKS cluster. Provides org management, SOUL layers,"
echo "    skills, audit, and multi-runtime agent management."
read -rp "  Enable admin console? [y/N]: " ADMIN_CHOICE
ENABLE_ADMIN=false
if [[ "${ADMIN_CHOICE}" =~ ^[yY]$ ]]; then
  ENABLE_ADMIN=true
fi

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${BOLD}Deployment Summary${NC}"
echo -e "  ${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  Region:        ${CYAN}${REGION}${NC}"
echo -e "  Cluster:       ${CYAN}${NAME}${NC}"
echo -e "  Architecture:  ${CYAN}${ARCH}${NC}"
echo -e "  Firecracker:   ${CYAN}${ENABLE_FC}${NC}"
echo -e "  Admin Console: ${CYAN}${ENABLE_ADMIN}${NC}"
if $IS_CHINA; then
echo -e "  Partition:     ${YELLOW}aws-cn${NC}"
fi
echo ""

# --- Cost estimate ---
COST="~\$380/month"
if $ENABLE_FC; then
  COST="~\$380/month + bare-metal on-demand (~\$4/hr when active)"
fi
echo -e "  Estimated cost: ${YELLOW}${COST}${NC} (EKS + 2 nodes + NAT + EFS)"
echo ""

read -rp "  Proceed? [Y/n]: " CONFIRM
if [[ "${CONFIRM}" =~ ^[nN]$ ]]; then
  echo "  Cancelled."
  exit 0
fi

# ─────────────────────────────────────────────────────────────────────────────
# Generate tfvars
# ─────────────────────────────────────────────────────────────────────────────
GENERATED="${TF_DIR}/generated.auto.tfvars"

cat > "$GENERATED" <<EOF
# Auto-generated by install.sh wizard — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
region           = "${REGION}"
name             = "${NAME}"
architecture     = "${ARCH}"
enable_efs       = true
enable_kata      = ${ENABLE_FC}
kata_hypervisor  = "fc"
enable_karpenter = ${ENABLE_KARPENTER}
EOF

echo ""
echo -e "${YELLOW}  Generated: ${GENERATED}${NC}"

# ─────────────────────────────────────────────────────────────────────────────
# China: run mirror script BEFORE terraform apply
# ─────────────────────────────────────────────────────────────────────────────
if $IS_CHINA; then
  echo ""
  echo -e "${YELLOW}  China region detected — mirroring images and Helm charts to ECR...${NC}"
  echo -e "  This is ${BOLD}required${NC} before terraform apply (ghcr.io, quay.io, Docker Hub are blocked)."
  echo ""
  MIRROR_SCRIPT="${SCRIPT_DIR}/china-image-mirror.sh"
  if [[ -f "$MIRROR_SCRIPT" ]]; then
    MIRROR_ARGS="--region ${REGION} --name ${NAME}"
    if [[ -n "${AWS_PROFILE:-}" ]]; then
      MIRROR_ARGS="$MIRROR_ARGS --profile ${AWS_PROFILE}"
    fi
    bash "$MIRROR_SCRIPT" $MIRROR_ARGS
  else
    echo -e "${RED}  Error: china-image-mirror.sh not found at ${MIRROR_SCRIPT}${NC}"
    echo -e "  Run it manually: bash eks/scripts/china-image-mirror.sh --region ${REGION} --name ${NAME}"
    exit 1
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# Deploy EKS + Operator
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}  [1/2] Deploying EKS cluster + OpenClaw operator...${NC}"
cd "$TF_DIR"
terraform init -input=false
terraform apply -auto-approve

CLUSTER_NAME=$(terraform output -raw cluster_name)
CLUSTER_REGION=$(terraform output -raw configure_kubectl | grep -oP '(?<=--region )\S+')

echo ""
echo -e "${GREEN}  EKS cluster deployed.${NC}"

# Configure kubectl
eval "$(terraform output -raw configure_kubectl)" 2>/dev/null

# ─────────────────────────────────────────────────────────────────────────────
# Deploy Admin Console (if enabled)
# ─────────────────────────────────────────────────────────────────────────────
if $ENABLE_ADMIN; then
  echo ""
  echo -e "${YELLOW}  [2/2] Admin console deployment...${NC}"
  echo -e "  ${CYAN}The admin console is deployed via CloudFormation on EC2.${NC}"
  echo -e "  ${CYAN}See: enterprise/deploy.sh in the repo root.${NC}"
  echo ""
  echo -e "  To deploy it now, run in a separate terminal:"
  echo -e "    ${BOLD}cd $(dirname "$SCRIPT_DIR")/../enterprise && bash deploy.sh${NC}"
  echo ""
  echo -e "  Then configure it to use this EKS cluster:"
  echo -e "    EKS_CLUSTER_NAME=${CLUSTER_NAME}"
  echo -e "    BEDROCK_ROLE_ARN=$(terraform output -raw bedrock_role_arn)"
else
  echo ""
  echo -e "${YELLOW}  [2/2] Skipping admin console (operator-only mode).${NC}"
  echo -e "  Deploy instances with: kubectl apply -f manifests/examples/openclaw-bedrock-instance.yaml"
fi

if $IS_CHINA; then
  echo ""
  echo -e "${YELLOW}  China region:${NC} images mirrored to ECR. When deploying OpenClaw instances, set:"
  echo -e "    ${BOLD}spec.registry${NC}: your China ECR endpoint"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  ╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}  ║          Deployment Complete                 ║${NC}"
echo -e "${GREEN}${BOLD}  ╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  kubectl:   ${CYAN}$(terraform output -raw configure_kubectl)${NC}"
echo -e "  cluster:   ${CYAN}${CLUSTER_NAME}${NC}"
echo -e "  operator:  ${CYAN}$(terraform output -raw operator_namespace)${NC}"
echo -e "  namespace: ${CYAN}$(terraform output -raw openclaw_namespace)${NC}"
echo -e "  bedrock:   ${CYAN}$(terraform output -raw bedrock_role_arn)${NC}"
echo ""
